version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 8888:8889
    volumes:
      - type: bind
        source: ./backend
        target: /api
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 5435:5436
    volumes:
      - ./data:/var/lib/mysql
