version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 8888:8889
    volumes:
      - ./backend_app/:/app

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 5435:5436
    volumes:
      - ./data:/var/lib/mysql
