version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/app/Dockerfile
    tty: true
    volumes:
      - type: bind
        source: ./backend
        target: /api
    ports:
      - "3000:3000"

  db:
    build:
      context: .
      dockerfile: ./docker/backend/db/Dockerfile
    ports:
      - 5435:5436
    volumes:
      - ./data:/var/lib/mysql

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/app/Dockerfile
    tty: true
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    ports:
      - "3333:3333"
