version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/app/Dockerfile
    tty: true
    volumes:
      - type: bind
        source: ./backend
        target: /api
    ports:
      - "3000:8080"

  db:
    image: postgres:alpine
    container_name: foreign_news_db
    tty: true
    # volumes:
    #    - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm
      POSTGRES_DB: gorm
    ports:
      - 5432:5432

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/app/Dockerfile
    tty: true
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    ports:
      - "4545:3333"
